# Generated by Django 3.0.8 on 2020-07-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Başlığınız', max_length=100, null=True, verbose_name='Başlık')),
                ('content', models.TextField(help_text='İçeriğiniz', max_length=1000, null=True, verbose_name='İçerik')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Zaman')),
            ],
        ),
    ]
