# Generated by Django 3.0.8 on 2020-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Gönderiler'},
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(help_text='İçeriğinizi Girin..', max_length=1000, null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Başlığınızı Girin..', max_length=100, null=True, verbose_name='Başlık'),
        ),
    ]
