# Generated by Django 3.0.8 on 2020-07-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_kategoriler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='kategoriler',
            field=models.ManyToManyField(related_name='blog', to='blog.Kategori'),
        ),
    ]
