# Generated by Django 3.0.8 on 2020-07-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(help_text='İçeriğinizi Girin', max_length=1000, null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to='', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='kategoriler',
            field=models.ManyToManyField(help_text='Kategorilerinizi Seçiniz', related_name='blog', to='blog.Kategori'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Başlığınızı Girin', max_length=100, null=True, verbose_name='Başlık'),
        ),
    ]
