# Generated by Django 3.0.8 on 2020-07-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200716_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/python_django.jpg', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to='blog', verbose_name='Resim'),
        ),
    ]
