# Generated by Django 3.0.8 on 2020-07-23 11:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/python_django.jpg', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to=blog.models.upload_to, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
