# Generated by Django 3.0.8 on 2020-07-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_yayin_taslak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(choices=[(None, 'Lütfen Birini Seçiniz.'), ('yayin', 'YAYIN'), ('taslak', 'TASLAK')], max_length=6, null=True),
        ),
    ]
