# Generated by Django 3.0.8 on 2020-08-16 17:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200723_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id'], 'verbose_name_plural': 'Gönderiler'},
        ),
        migrations.AddField(
            model_name='blog',
            name='content1',
            field=ckeditor.fields.RichTextField(max_length=5000, null=True, verbose_name='İçerik1'),
        ),
    ]
